[package]
name = "development"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
common = { path = "../common" }
tokio = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true }
notify = "7.0.0"
grass = "0.13.4"
