max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_impl_items = true
merge_derives = true
force_explicit_abi = false
enum_discrim_align_threshold = 20
match_arm_blocks = true
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_indent = "Block"