appenders:
  stderr:
    kind: console
    target: stderr
    encoder:
      pattern: "{d(%Y-%d-%m %H:%M:%S)} - |{l}| - [{M}] - {m}\n"
  logfile:
    kind: rolling_file
    path: "./logs/latest.log"
    filters:
      - kind: threshold
        level: warn
    encoder:
      pattern: "{d(%Y-%d-%m %H:%M:%S)} - |{l}| - [{M}] - {m}\n"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 5 mb
      roller:
        kind: fixed_window
        pattern: "/logs/archive/{}.log"
        count: 50
root:
  level: info
  appenders:
    - stderr
    - logfile