[package]
name = "rinja_axum"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
fluent-templates = { workspace = true }

rinja = { git = "https://github.com/rinja-rs/rinja.git", branch = "master" }
http = "1.2.0"