[package]
name = "rinja_axum"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
rinja = { git = "https://github.com/rinja-rs/rinja.git", branch = "master" }
axum-core = "0.5.0-rc.1"
http = "1.2.0"